using System;
using System.Net;
using System.Net.Mail;
using System.Text;
using System.Web.Mvc;
using Sitio.Models;

namespace Sitio.Controllers
{
	[Route("Home/{action=index}")]
	public class ServicesController : Controller
	{
		// GET: home
		public ActionResult Index(string service)
		{
			var longDesc = "";
			switch (service)
			{
				case "accidentesEnTransportePublico":
					longDesc = @"<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar/ amigo ha sufrido un accidente mientras viajaba en un medio de transporte p&uacute;blico (colectivo, tren, taxi, remis o subte), debe asesorarse con profesionales de su confianza que le brinden el </span><strong>mejor servicio al menor costo</strong><span style=""font-weight: 400;"">. Le </span><strong>garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su indemnizaci&oacute;n brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso</strong><span style=""font-weight: 400;"">. </span><span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente.</strong></span></p>
					<p><span style=""font-weight: 400;"">Es posible que las lesiones sufridas en un accidente de tr&aacute;nsito no aparenten gravedad y no exista intervenci&oacute;n m&eacute;dica en el lugar. En esos casos, es fundamental que usted </span><strong>busque atenci&oacute;n m&eacute;dica inmediatamente despu&eacute;s del accidente</strong><span style=""font-weight: 400;"">. Tal vez usted crea que el choque fue menor y que el mismo no produjo un da&ntilde;o en su salud, pero debe tener presente que </span><strong>algunas lesiones (aunque usted no sienta dolor inicialmente o no resulten visibles) se manifiestan varios d&iacute;as despu&eacute;s del siniestro</strong><span style=""font-weight: 400;"">. Si usted deja pasar tiempo sin recibir atenci&oacute;n m&eacute;dica, &uacute;nicamente lograr&aacute; que la compa&ntilde;&iacute;a de seguros disminuya su indemnizaci&oacute;n al reclamar lesiones. Tenga presente que al ser atendido siempre debe </span><strong>reclamar las constancias m&eacute;dicas</strong><span style=""font-weight: 400;""> y todos los estudios que le hayan realizado.</span></p>
					<p><span style=""font-weight: 400;"">Siempre recordamos a nuestros clientes, la importancia ante estos sucesos de contar con toda la informaci&oacute;n posible a su alcance. Es por ello que recomendamos, </span><strong>conservar el boleto/ tarjeta SUBE, tomar los datos del transporte donde usted viajaba al producirse el accidente, de testigos y otras v&iacute;ctimas del siniestro y de cualquier otro veh&iacute;culo involucrado</strong><span style=""font-weight: 400;"">. Tambi&eacute;n resaltamos la importancia de </span><strong>tomar fotos</strong><span style=""font-weight: 400;""> en donde se pueda apreciar la zona en que cada veh&iacute;culo sufri&oacute; da&ntilde;os.</span></p>
					<p><span style=""font-weight: 400;"">Por &uacute;ltimo, le recomendamos que </span><strong>no firme acuerdos directamente con la aseguradora. El negocio de las empresas de seguros es pagarle a usted lo menos posible</strong><span style=""font-weight: 400;"">. Es por eso que har&aacute;n parecer justa la suma que le ofrecen, pero lo &uacute;nico que buscan es cerrar el tema por la m&iacute;nima cantidad posible. </span></p>
					<p><span style=""font-weight: 400;"">Cuando usted se asesora con nosotros, debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad del choque y que le pague el m&aacute;ximo obtenible. </span><strong>Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted</strong><span style=""font-weight: 400;"">. Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que </span><strong>cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio, termina pag&aacute;ndole m&aacute;s para evitar los costos del mismo.</strong></p>
					<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar</strong><span style=""font-weight: 400;""> el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
					break;
				case "accidentesEnAuto":
					longDesc = @"<p><span style=""font-weight: 400;"">Es importante remarcar, que cuando se inicia un reclamo ante una compa&ntilde;&iacute;a de seguros, de realizarlo con la representaci&oacute;n de un </span><strong>abogado</strong><span style=""font-weight: 400;"">, usted siempre percibir&aacute; un monto indemnizatorio superior</span><span style=""font-weight: 400;"">.</span></p>
						<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar/ amigo ha sufrido un accidente con su veh&iacute;culo ya sea por culpa de un tercero o compartida, usted posee el derecho de realizar el reclamo de una </span><strong>indemnizaci&oacute;n justa</strong><span style=""font-weight: 400;"">, a fin de resarcir los da&ntilde;os materiales, f&iacute;sicos y morales que pudiese haber padecido.</span></p>
						<p><span style=""font-weight: 400;"">Por esa raz&oacute;n,</span><span style=""font-weight: 400;""> usted</span><span style=""font-weight: 400;""> debe asesorarse con profesionales de su confianza que le brinden el </span><strong>mejor servicio al menor costo. </strong><span style=""font-weight: 400;"">Le</span><strong> garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su indemnizaci&oacute;n brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso. </strong><span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente.</strong></span></p>
						<p><span style=""font-weight: 400;"">Es posible que las lesiones sufridas en un accidente de tr&aacute;nsito no aparenten gravedad y no exista intervenci&oacute;n m&eacute;dica en el lugar. En esos casos, es fundamental que usted y sus acompa&ntilde;antes </span><strong>busquen atenci&oacute;n m&eacute;dica inmediatamente despu&eacute;s del accidente</strong><span style=""font-weight: 400;"">. Tal vez usted crea que el choque fue menor y que el mismo no produjo un da&ntilde;o en su salud, pero debe tener presente que </span><strong>algunas lesiones (aunque usted no sienta dolor inicialmente o no resulten visibles) se manifiestan varios d&iacute;as despu&eacute;s del siniestro</strong><span style=""font-weight: 400;"">. Si usted deja pasar tiempo sin recibir atenci&oacute;n m&eacute;dica, &uacute;nicamente lograr&aacute; que la compa&ntilde;&iacute;a de seguros disminuya su indemnizaci&oacute;n al reclamar lesiones. Tenga presente que al ser atendido siempre debe </span><strong>reclamar las constancias m&eacute;dicas</strong><span style=""font-weight: 400;""> y todos los estudios que le hayan realizado.&nbsp;</span></p>
						<p><strong>Siempre recordamos a nuestros clientes, la importancia ante estos sucesos de contar con toda la informaci&oacute;n posible a su alcance. Es por ello, que recomendamos tomar los datos del transporte donde se produjo el accidente, de testigos y otras v&iacute;ctimas del siniestro y de cualquier otro veh&iacute;culo involucrado. Tambi&eacute;n resaltamos la importancia de tomar fotos en donde se pueda apreciar la zona en que cada veh&iacute;culo sufri&oacute; da&ntilde;os.</strong></p>
						<p><span style=""font-weight: 400;"">Por &uacute;ltimo, le recomendamos que </span><strong>no firme acuerdos directamente con la aseguradora. El negocio de las empresas de seguros es pagarle a usted lo menos posible</strong><span style=""font-weight: 400;"">. Es por eso que har&aacute;n parecer justa la suma que le ofrecen, pero lo &uacute;nico que buscan es cerrar el tema por la m&iacute;nima cantidad posible. </span></p>
						<p><span style=""font-weight: 400;"">Cuando usted se asesora con nosotros, debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad del choque y que le pague el m&aacute;ximo obtenible. </span><strong>Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted</strong><span style=""font-weight: 400;"">. Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que </span><strong>cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio, termina pag&aacute;ndole m&aacute;s para evitar los costos del mismo.</strong></p>
						<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar</strong><span style=""font-weight: 400;""> el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
			
					break;

				case "accidentesEnMoto":
					longDesc =
						@"<p><span style=""font-weight: 400;"">Es importante remarcar, al iniciar un reclamo ante una compa&ntilde;&iacute;a de seguros, que de realizarlo con la representaci&oacute;n de un </span><strong>abogado especializado</strong><span style=""font-weight: 400;"">, usted siempre percibir&aacute; un </span><strong>monto indemnizatorio mayor.</strong></p>
							<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar/ amigo ha sufrido un accidente con su veh&iacute;culo ya sea por culpa de un tercero o compartida, usted posee el derecho de realizar el reclamo de una indemnizaci&oacute;n justa, a fin de resarcir los da&ntilde;os materiales, f&iacute;sicos y morales que pudiese haber padecido.</span></p>
							<p><span style=""font-weight: 400;"">Por esa raz&oacute;n</span><span style=""font-weight: 400;""> usted</span><span style=""font-weight: 400;""> debe asesorarse con profesionales de su confianza que le brinden el </span><strong>mejor servicio al menor costo</strong><span style=""font-weight: 400;"">. Le garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su indemnizaci&oacute;n brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso.</span> <span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente.</strong></span></p>
							<p><span style=""font-weight: 400;"">Es posible que las lesiones sufridas en un accidente de tr&aacute;nsito no aparenten gravedad y no exista intervenci&oacute;n m&eacute;dica en el lugar. En esos casos, es fundamental que usted y sus acompa&ntilde;antes </span><strong>busquen atenci&oacute;n m&eacute;dica inmediatamente despu&eacute;s del accidente</strong><span style=""font-weight: 400;"">. Tal vez usted crea que el choque fue menor y que el mismo no produjo un da&ntilde;o en su salud, pero debe tener presente que </span><strong>algunas lesiones (aunque usted no sienta dolor inicialmente o no resulten visibles) se manifiestan varios d&iacute;as despu&eacute;s del siniestro</strong><span style=""font-weight: 400;"">. Si usted deja pasar tiempo sin recibir atenci&oacute;n m&eacute;dica, &uacute;nicamente lograr&aacute; que la compa&ntilde;&iacute;a de seguros disminuya su indemnizaci&oacute;n al reclamar lesiones. Tenga presente que al ser atendido siempre debe </span><strong>reclamar las constancias m&eacute;dicas</strong><span style=""font-weight: 400;""> y todos los estudios que le hayan realizado.</span></p>
							<p><strong>Siempre recordamos a nuestros clientes, la importancia ante estos sucesos de contar con toda la informaci&oacute;n posible a su alcance. Es por ello, que recomendamos tomar los datos del transporte donde se produjo el accidente, de testigos y otras v&iacute;ctimas del siniestro y de cualquier otro veh&iacute;culo involucrado. Tambi&eacute;n resaltamos la importancia de tomar fotos en donde se pueda apreciar la zona en que cada veh&iacute;culo sufri&oacute; da&ntilde;os.</strong></p>
							<p><span style=""font-weight: 400;"">Por &uacute;ltimo, le recomendamos que </span><strong>no firme acuerdos directamente con la aseguradora. El negocio de las empresas de seguros es pagarle a usted lo menos posible</strong><span style=""font-weight: 400;"">. Es por eso que har&aacute;n parecer justa la suma que le ofrecen, pero lo &uacute;nico que buscan es cerrar el tema por la m&iacute;nima cantidad posible. </span></p>
							<p><span style=""font-weight: 400;"">Cuando usted se asesora con nosotros, debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad del choque y que le pague el m&aacute;ximo obtenible. </span><strong>Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted</strong><span style=""font-weight: 400;"">. Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que </span><strong>cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio, termina pag&aacute;ndole m&aacute;s para evitar los costos del mismo.</strong></p>
							<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar</strong><span style=""font-weight: 400;""> el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
					break;

				case "accidentesEnBicicleta":
					longDesc =
						@"<p><span style=""font-weight: 400;""> &nbsp;</span><strong>Todo siniestro en bicicleta puede ser indemnizado. Circulando por la bicisenda o fuera de ella usted tiene prioridad. Inicie con nosotros su reclamo por lesiones en ocasi&oacute;n de un accidente de transito. </strong></p>
						<p><span style=""font-weight: 400;"">Es importante remarcar, que en el caso de ser una compa&ntilde;&iacute;a de seguros ante quien se presente el reclamo extrajudicial y/o judicial, de realizarlo con la representaci&oacute;n de un </span><strong>abogado especializado</strong><span style=""font-weight: 400;"">, usted siempre percibir&aacute; un </span><strong>monto indemnizatorio superior.</strong><span style=""font-weight: 400;""> </span></p>
						<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar/ amigo ha sufrido un accidente con su veh&iacute;culo ya sea por culpa de un tercero o compartida, usted posee el derecho de realizar el reclamo de una indemnizaci&oacute;n justa, a fin de resarcir los da&ntilde;os materiales, f&iacute;sicos y morales que pudiese haber padecido.</span></p>
						<p><span style=""font-weight: 400;"">Por esa razon</span><span style=""font-weight: 400;""> usted</span><span style=""font-weight: 400;""> debe asesorarse con profesionales de su confianza que le brinden el </span><strong>mejor servicio al menor costo</strong><span style=""font-weight: 400;"">. Le garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su indemnizaci&oacute;n brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso.</span> <span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente.</strong></span></p>
						<p><span style=""font-weight: 400;"">Es posible que las lesiones sufridas en un accidente de tr&aacute;nsito no aparenten gravedad y no exista intervenci&oacute;n m&eacute;dica en el lugar. En esos casos, es fundamental que usted y sus acompa&ntilde;antes </span><strong>busquen atenci&oacute;n m&eacute;dica inmediatamente despu&eacute;s del accidente</strong><span style=""font-weight: 400;"">. Tal vez usted crea que el choque fue menor y que el mismo no produjo un da&ntilde;o en su salud, pero debe tener presente que </span><strong>algunas lesiones (aunque usted no sienta dolor inicialmente o no resulten visibles) se manifiestan varios d&iacute;as despu&eacute;s del siniestro</strong><span style=""font-weight: 400;"">. Si usted deja pasar tiempo sin recibir atenci&oacute;n m&eacute;dica, &uacute;nicamente lograr&aacute; que la compa&ntilde;&iacute;a de seguros disminuya su indemnizaci&oacute;n al reclamar lesiones. Tenga presente que al ser atendido siempre debe </span><strong>reclamar las constancias m&eacute;dicas</strong><span style=""font-weight: 400;""> y todos los estudios que le hayan realizado. </span></p>
						<p><strong>Siempre recordamos a nuestros clientes, la importancia ante estos sucesos de contar con toda la informaci&oacute;n posible a su alcance. Es por ello, que recomendamos tomar los datos del transporte donde se produjo el accidente, de testigos y otras v&iacute;ctimas del siniestro y de cualquier otro veh&iacute;culo involucrado. Tambi&eacute;n resaltamos la importancia de tomar fotos en donde se pueda apreciar la zona en que cada veh&iacute;culo sufri&oacute; da&ntilde;os.</strong></p>
						<p><span style=""font-weight: 400;"">Por &uacute;ltimo, le recomendamos que </span><strong>no firme acuerdos directamente con la aseguradora. El negocio de las empresas de seguros es pagarle a usted lo menos posible</strong><span style=""font-weight: 400;"">. Es por eso que har&aacute;n parecer justa la suma que le ofrecen, pero lo &uacute;nico que buscan es cerrar el tema por la m&iacute;nima cantidad posible. </span></p>
						<p><span style=""font-weight: 400;"">Cuando usted se asesora con nosotros, debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad del choque y que le pague el m&aacute;ximo obtenible. </span><strong>Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted</strong><span style=""font-weight: 400;"">. Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que </span><strong>cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio, termina pag&aacute;ndole m&aacute;s para evitar los costos del mismo.</strong></p>
						<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar</strong><span style=""font-weight: 400;""> el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
					break;
				case "accidentesComoAcompanantes":
					longDesc =
						@"<p><span style=""font-weight: 400;"">Al momento de ocurrir un accidente</span><strong>, un pasajero nunca es culpable. Incluso aunque viaje en el veh&iacute;culo del conductor que ocasion&oacute; el accidente.</strong><span style=""font-weight: 400;""> Es por esto que si usted sufri&oacute; un accidente como pasajero o acompa&ntilde;ante, siempre se encuentra amparado por la ley y posee el derecho de realizar el reclamo de una indemnizaci&oacute;n justa, a fin de resarcir los da&ntilde;os materiales, f&iacute;sicos y morales que pudiese haber padecido.</span></p>
							<p><strong>En general, los accidentados como acompa&ntilde;antes no presentan el reclamo para no generarle un problema al due&ntilde;o del veh&iacute;culo, a quien conocen y no desean perjudicar. Si este &uacute;ltimo posee su seguro al d&iacute;a, la compa&ntilde;&iacute;a de seguros ser&aacute; la que responda. El due&ntilde;o del veh&iacute;culo no se ver&aacute; perjudicado de ninguna forma.</strong></p>
							<p><span style=""font-weight: 400;"">Tenga en cuenta que si usted tuvo lesiones a consecuencia del accidente</span><strong>, ser representado por el mismo abogado que el conductor del veh&iacute;culo en el que viajaba, podr&iacute;a crear conflictos de intereses para el abogado.</strong><span style=""font-weight: 400;""> En general, los pasajeros lastimados en un accidente, tienen mejores resultados cuando son representados por su propio abogado.</span></p>
							<p><span style=""font-weight: 400;"">Es importante remarcar, que en el caso de ser una compa&ntilde;&iacute;a de seguros ante quien se presente el reclamo extrajudicial y/o judicial, de realizarlo con la representaci&oacute;n de un </span><strong>abogado especializado</strong><span style=""font-weight: 400;"">, usted siempre recibir&aacute; un </span><span style=""font-weight: 400;""><span style=""text-decoration: underline;"">monto indemnizatorio superior</span>.</span></p>
							<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar/ amigo ha sufrido un accidente con su veh&iacute;culo ya sea por culpa de un tercero o compartida, usted posee el derecho de realizar el reclamo de una indemnizaci&oacute;n justa, a fin de resarcir los da&ntilde;os materiales, f&iacute;sicos y morales que pudiese haber padecido.</span></p>
							<p><span style=""font-weight: 400;"">Por esa raz&oacute;n</span><span style=""font-weight: 400;""> usted</span><span style=""font-weight: 400;""> debe asesorarse con profesionales de su confianza que le brinden el </span><strong>mejor servicio al menor costo</strong><span style=""font-weight: 400;"">. Le garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su indemnizaci&oacute;n brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso.</span> <span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente.</strong></span></p>
							<p><span style=""font-weight: 400;"">Es posible que las lesiones sufridas en un accidente de tr&aacute;nsito no aparenten gravedad y no exista intervenci&oacute;n m&eacute;dica en el lugar. En esos casos, es fundamental que usted y sus acompa&ntilde;antes </span><strong>busquen atenci&oacute;n m&eacute;dica inmediatamente despu&eacute;s del accidente</strong><span style=""font-weight: 400;"">. Tal vez usted crea que el choque fue menor y que el mismo no produjo un da&ntilde;o en su salud, pero debe tener presente que </span><strong>algunas lesiones (aunque usted no sienta dolor inicialmente o no resulten visibles) se manifiestan varios d&iacute;as despu&eacute;s del siniestro</strong><span style=""font-weight: 400;"">. Si usted deja pasar tiempo sin recibir atenci&oacute;n m&eacute;dica, &uacute;nicamente lograr&aacute; que la compa&ntilde;&iacute;a de seguros disminuya su indemnizaci&oacute;n al reclamar lesiones. Tenga presente que al ser atendido siempre debe </span><strong>reclamar las constancias m&eacute;dicas</strong><span style=""font-weight: 400;""> y todos los estudios que le hayan realizado.</span></p>
							<p><strong>Siempre recordamos a nuestros clientes, la importancia ante estos sucesos de contar con toda la informaci&oacute;n posible a su alcance. Es por ello, que recomendamos tomar los datos del transporte donde se produjo el accidente, de testigos y otras v&iacute;ctimas del siniestro y de cualquier otro veh&iacute;culo involucrado. Tambi&eacute;n resaltamos la importancia de tomar fotos en donde se pueda apreciar la zona en que cada veh&iacute;culo sufri&oacute; da&ntilde;os.</strong></p>
							<p><span style=""font-weight: 400;"">Por &uacute;ltimo, le recomendamos que </span><strong>no firme acuerdos directamente con la aseguradora. El negocio de las empresas de seguros es pagarle a usted lo menos posible</strong><span style=""font-weight: 400;"">. Es por eso que har&aacute;n parecer justa la suma que le ofrecen, pero lo &uacute;nico que buscan es cerrar el tema por la m&iacute;nima cantidad posible. </span></p>
							<p><span style=""font-weight: 400;"">Cuando usted se asesora con nosotros, debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad del choque y que le pague el m&aacute;ximo obtenible. </span><strong>Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted</strong><span style=""font-weight: 400;"">. Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que </span><strong>cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio, termina pag&aacute;ndole m&aacute;s para evitar los costos del mismo.</strong></p>
							<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar</strong><span style=""font-weight: 400;""> el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
					break;

				case "accidentesComoPeaton":
					longDesc =
						@"<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar ha sufrido un accidente como peat&oacute;n, </span><strong>cuente con nosotros</strong><span style=""font-weight: 400;""> para realizar las acciones legales correspondientes, a fin de realizar el reclamo de una </span><strong>indemnizaci&oacute;n justa.</strong></p>
					<p><span style=""font-weight: 400;"">Es importante remarcar, que en el caso de ser una compa&ntilde;&iacute;a de seguros ante quien se presente el reclamo extrajudicial y/o judicial, de realizarlo con la representaci&oacute;n de un </span><strong>abogado especializado</strong><span style=""font-weight: 400;"">, usted siempre recibir&aacute; un </span><strong>monto indemnizatorio superior.</strong></p>
					<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar/ amigo ha sufrido un accidente con su veh&iacute;culo ya sea por culpa de un tercero o compartida, usted posee el derecho de realizar el reclamo de una indemnizaci&oacute;n justa, a fin de resarcir los da&ntilde;os materiales, f&iacute;sicos y morales que pudiese haber padecido.</span></p>
					<p><span style=""font-weight: 400;"">Por esa raz&oacute;n</span><span style=""font-weight: 400;""> usted</span><span style=""font-weight: 400;""> debe asesorarse con profesionales de su confianza que le brinden el </span><strong>mejor servicio al menor costo</strong><span style=""font-weight: 400;"">. Le garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su indemnizaci&oacute;n brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso. </span><span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente.</strong></span></p>
					<p><span style=""font-weight: 400;"">Es posible que las lesiones sufridas en un accidente de tr&aacute;nsito no aparenten gravedad y no exista intervenci&oacute;n m&eacute;dica en el lugar. En esos casos, es fundamental que usted y sus acompa&ntilde;antes </span><strong>busquen atenci&oacute;n m&eacute;dica inmediatamente despu&eacute;s del accidente</strong><span style=""font-weight: 400;"">. Tal vez usted crea que el choque fue menor y que el mismo no produjo un da&ntilde;o en su salud, pero debe tener presente que </span><strong>algunas lesiones (aunque usted no sienta dolor inicialmente o no resulten visibles) se manifiestan varios d&iacute;as despu&eacute;s del siniestro</strong><span style=""font-weight: 400;"">. Si usted deja pasar tiempo sin recibir atenci&oacute;n m&eacute;dica, &uacute;nicamente lograr&aacute; que la compa&ntilde;&iacute;a de seguros disminuya su indemnizaci&oacute;n al reclamar lesiones. Tenga presente que al ser atendido siempre debe </span><strong>reclamar las constancias m&eacute;dicas</strong><span style=""font-weight: 400;""> y todos los estudios que le hayan realizado.</span></p>
					<p><strong>Siempre recordamos a nuestros clientes, la importancia ante estos sucesos de contar con toda la informaci&oacute;n posible a su alcance. Es por ello, que recomendamos tomar los datos del transporte donde se produjo el accidente, de testigos y otras v&iacute;ctimas del siniestro y de cualquier otro veh&iacute;culo involucrado. Tambi&eacute;n resaltamos la importancia de tomar fotos en donde se pueda apreciar la zona en que cada veh&iacute;culo sufri&oacute; da&ntilde;os.</strong></p>
					<p><span style=""font-weight: 400;"">Por &uacute;ltimo, le recomendamos que </span><strong>no firme acuerdos directamente con la aseguradora. El negocio de las empresas de seguros es pagarle a usted lo menos posible</strong><span style=""font-weight: 400;"">. Es por eso que har&aacute;n parecer justa la suma que le ofrecen, pero lo &uacute;nico que buscan es cerrar el tema por la m&iacute;nima cantidad posible. </span></p>
					<p><span style=""font-weight: 400;"">Cuando usted se asesora con nosotros, debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad del choque y que le pague el m&aacute;ximo obtenible. </span><strong>Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted</strong><span style=""font-weight: 400;"">. Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que </span><strong>cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio, termina pag&aacute;ndole m&aacute;s para evitar los costos del mismo.</strong></p>
					<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar</strong><span style=""font-weight: 400;""> el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
					break;

				case "choqueSinSeguro":
					longDesc =
						@"<p><span style=""font-weight: 400;"">Es importante remarcar, al iniciar un reclamo ante una compa&ntilde;&iacute;a de seguros, que de realizarlo con la representaci&oacute;n de un </span><strong>abogado especializado</strong><span style=""font-weight: 400;"">, usted siempre percibir&aacute; un </span><strong>monto indemnizatorio mayor.</strong></p>
							<p><strong>Si usted ha sufrido un accidente de tr&aacute;nsito por culpa de un tercero tiene derecho a reclamar aunque su seguro no estuviera vigente.</strong></p>
							<p><span style=""font-weight: 400;"">A veces uno puede pensar que si no contaba con cobertura (por ejemplo, porque olvid&oacute; pagar la cuota a tiempo) no puede iniciar el reclamo correspondiente. Aclaramos qu&eacute; este es un error bastante com&uacute;n entre la gente. M&aacute;s a&uacute;n cuando usted va a consultar a la compa&ntilde;&iacute;a del tercero sin asesor&iacute;a y de all&iacute; lo derivan a su propio seguro a realizar la denuncia administrativa. Es decir, el seguro del tercero lo deriva a su propio seguro. Cuando usted llega a su seguro, lo vuelven a derivar al seguro del tercero y asi sucesivamente agot&aacute;ndolo y confundi&eacute;ndolo hasta que usted finalmente se resigna y abandona el reclamo.</span></p>
							<p><strong>Lo que usted debe hacer en estos casos es contactarnos r&aacute;pidamente y obtener asi la soluci&oacute;n que necesita para cobrar lo que le corresponde.</strong></p>
							<p><span style=""font-weight: 400;"">U</span><span style=""font-weight: 400;"">sted </span><span style=""font-weight: 400;"">debe asesorarse siempre con profesionales de su confianza que le brinden el</span><strong> mejor servicio al menor costo. </strong><span style=""font-weight: 400;"">Nosotros le garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su indemnizaci&oacute;n brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso. </span><span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente. </strong></span></p>
							<p><span style=""font-weight: 400;"">Es posible que las lesiones sufridas en un accidente de tr&aacute;nsito no aparenten gravedad y no exista intervenci&oacute;n m&eacute;dica en el lugar. En esos casos, es fundamental que usted y sus acompa&ntilde;antes </span><strong>busquen atenci&oacute;n m&eacute;dica inmediatamente despu&eacute;s del accidente</strong><span style=""font-weight: 400;"">. Tal vez usted crea que el choque fue menor y que el mismo no produjo un da&ntilde;o en su salud, pero debe tener presente que </span><strong>algunas lesiones (aunque usted no sienta dolor inicialmente o no resulten visibles) se manifiestan varios d&iacute;as despu&eacute;s del siniestro</strong><span style=""font-weight: 400;"">. Si usted deja pasar tiempo sin recibir atenci&oacute;n m&eacute;dica, &uacute;nicamente lograr&aacute; que la compa&ntilde;&iacute;a de seguros disminuya su indemnizaci&oacute;n al reclamar lesiones. Tenga presente que al ser atendido siempre debe </span><strong>reclamar las constancias m&eacute;dicas</strong><span style=""font-weight: 400;""> y todos los estudios que le hayan realizado.</span></p>
							<p><strong>Siempre recordamos a nuestros clientes, la importancia ante estos sucesos de contar con toda la informaci&oacute;n posible a su alcance. Es por ello, que recomendamos tomar los datos del transporte donde se produjo el accidente, de testigos y otras v&iacute;ctimas del siniestro y de cualquier otro veh&iacute;culo involucrado. Tambi&eacute;n resaltamos la importancia de tomar fotos en donde se pueda apreciar la zona en que cada veh&iacute;culo sufri&oacute; da&ntilde;os.</strong></p>
							<p><span style=""font-weight: 400;"">Por &uacute;ltimo, le recomendamos que </span><strong>no firme acuerdos directamente con la aseguradora. El negocio de las empresas de seguros es pagarle a usted lo menos posible</strong><span style=""font-weight: 400;"">. Es por eso que har&aacute;n parecer justa la suma que le ofrecen, pero lo &uacute;nico que buscan es cerrar el tema por la m&iacute;nima cantidad posible. </span></p>
							<p><span style=""font-weight: 400;"">Cuando usted se asesora con nosotros, debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad del choque y que le pague el m&aacute;ximo obtenible. </span><strong>Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted</strong><span style=""font-weight: 400;"">. Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que </span><strong>cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio, termina pag&aacute;ndole m&aacute;s para evitar los costos del mismo.</strong></p>
							<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar</strong><span style=""font-weight: 400;""> el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
					break;

				case "accidentesDeTrabajo":
					longDesc =
						@"<p><span style=""font-weight: 400;"">Si Ud. es v&iacute;ctima de un accidente en su trabajo, de un accidente in itinere (camino al trabajo o de regreso a su casa desde el trabajo) o de una enfermedad profesional, lo primero que debe hacer es informar a su empleador. Ser&aacute; su empleador quien informe a la ART lo sucedido (aunque tambi&eacute;n puede hacerlo usted mismo informando en forma directa a su ART).</span></p>
					<p><span style=""font-weight: 400;"">El paso siguiente es pedirle una copia de la denuncia a su empleador.</span></p>
					<p><span style=""font-weight: 400;"">Una vez iniciado el tratamiento m&eacute;dico en su ART, usted debe </span><strong>conservar todas las constancias m&eacute;dicas por m&iacute;nimas qu&eacute; sean</strong><span style=""font-weight: 400;"">, para poder acreditar en el futuro la atenci&oacute;n recibida.</span></p>
					<p><span style=""font-weight: 400;"">Durante este proceso le recordamos que siempre es fundamental asesorarse legalmente. </span></p>
					<p><strong>Tenga presente que, asi como en el caso de los seguros automotores, el negocio de las ARTs es pagarle a usted lo menos posible. En gran parte de los casos, pese a existir accidentes grav&iacute;simos y pruebas contundentes de secuelas, las ARTs brindan una atenci&oacute;n m&eacute;dica m&iacute;nima y luego le dan el alta al paciente sin ningun tipo de incapacidad o con un porcentaje muy bajo.</strong></p>
					<p><span style=""font-weight: 400;"">Si usted ya atraves&oacute; este proceso y no est&aacute; de acuerdo con la incapacidad que le asign&oacute; su ART a&uacute;n est&aacute; a tiempo de asesorarse. </span></p>
					<p><span style=""font-weight: 400;"">A grandes rasgos, </span><strong>el procedimiento que siguen las ART es el de notificar el alta (con o sin incapacidad) por carta documento, inform&aacute;ndole a usted que tiene la posibilidad de concurrir a </strong><span style=""text-decoration: underline;""><strong>Comisi&oacute;n M&eacute;dica</strong></span><strong> sin necesidad de abogado</strong><span style=""font-weight: 400;"">. Lamentablemente, </span><strong>este es un </strong><span style=""text-decoration: underline;""><strong>tr&aacute;mite administrativo ileg&iacute;timo que ha sido declarado inconstitucional por la propia Corte Suprema de Justicia</strong></span><span style=""font-weight: 400;"">. Ello debido a que </span><span style=""text-decoration: underline;""><strong>no interviene un Juez que garantice sus derechos y por si fuera poco lo empujan a concurrir sin un abogado de confianza con el conocimiento necesario para proteger sus intereses</strong><strong>.</strong></span></p>
					<p><strong>Se aprovechan del desconocimiento de la gente</strong><span style=""font-weight: 400;""> y bajo la apariencia de brindarle otra instancia de reclamo, lo que buscan es legitimar un procedimiento que permita pagarle a la v&iacute;ctima lo menos posible.</span></p>
					<p><span style=""text-decoration: underline;""><strong>No se deje enga&ntilde;ar</strong></span><span style=""font-weight: 400;"">, ante tales injusticias del sistema nosotros nos paramos del lado del trabajador a defender sus derechos.</span></p>
					<p><strong>Le recordamos que </strong><span style=""text-decoration: underline;""><strong>el reclamo se realiza directamente a la ART. Su empleador no tiene relaci&oacute;n alguna con el reclamo</strong></span><span style=""font-weight: 400;""> y la indemnizaci&oacute;n que reciba usted proviene &uacute;nicamente de la ART. Al realizar el reclamo usted no perjudica de ningun modo a su patron ni pone en riesgo su trabajo.</span></p>
					<p><span style=""font-weight: 400;"">Es fundamental resaltar este punto ya que </span><strong>mucha gente cree que al hacer un reclamo por accidente laboral perjudica a su empleador y por tener una idea equivocada elige resignar sus derechos.</strong></p>
					<p><strong><strong>Cons&uacute;ltenos</strong><span style=""font-weight: 400;""> y le explicaremos de qu&eacute; forma cobrar lo que responde sin arriesgar su empleo.</span></strong></p>";
					break;


				case "accidentesInItinere":
					longDesc = @"<p><span style=""font-weight: 400;"">Los accidentes in itinere (del latin &ldquo;itinere&rdquo;: &ldquo;en curso&rdquo;) se encuentran definidos en el art&iacute;culo sexto de la La Ley de Riesgos del Trabajo (Ley 24.557) como: &ldquo;todo acontecimiento s&uacute;bito y violento ocurrido por el hecho o en ocasi&oacute;n del trabajo, o en el trayecto entre el domicilio del trabajador y el lugar de trabajo, siempre y cuando el damnificado no hubiere interrumpido o alterado dicho trayecto por causas ajenas al trabajo&rdquo;.</span></p>
							<p><strong><span style=""text-decoration: underline;"">Ejemplo 1</span>:</strong> <strong>El trabajador, luego de salir de su casa</strong><span style=""font-weight: 400;""> y llegando al trabajo, </span><strong>sufre un robo</strong><span style=""font-weight: 400;""> con herida de arma blanca, con cortes en el brazo, ocurrido en el trayecto al trabajo.</span></p>
							<p><strong><span style=""text-decoration: underline;"">Ejemplo 2</span>:</strong><span style=""font-weight: 400;""> El trabajador, </span><strong>volviendo a su hogar al salir de su jornada, caminando por la vereda</strong><span style=""font-weight: 400;"">, pisa mal y cae con </span><strong>fractura de rodilla</strong><span style=""font-weight: 400;"">.</span></p>
							<p><span style=""font-weight: 400;"">Como se puede apreciar, </span><strong>es todo accidente sufrido por el trabajador en el trayecto entre el hogar y el trabajo, ya sea yendo o volviendo del mismo, siempre y cuando el damnificado no hubiere interrumpido o alterado dicho trayecto por causas ajenas al trabajo</strong><span style=""font-weight: 400;"">.</span></p>
							<p><span style=""font-weight: 400;"">En estos casos, la ART deber&aacute; brindar las prestaciones m&eacute;dicas y dinerarias hasta el alta m&eacute;dica o t&eacute;rmino legal, y si del accidente in itinere, han quedado secuelas tanto ps&iacute;quicas como f&iacute;sicas en la salud del trabajador, &eacute;ste tiene el derecho a ser indemnizado conforme la normativa vigente.</span></p>
							<p><strong>Tenga presente que, asi como en el caso de los seguros automotores, el negocio de las ARTs es pagarle a usted lo menos posible. En gran parte de los casos, pese a existir accidentes grav&iacute;simos y pruebas contundentes de secuelas, las ARTs brindan una atenci&oacute;n m&eacute;dica m&iacute;nima y luego le dan el alta al paciente sin ningun tipo de incapacidad o con un porcentaje muy bajo.</strong></p>
							<p><strong><strong>&nbsp;</strong></strong></p>
							<p><span style=""text-decoration: underline;""><strong>No se deje enga&ntilde;ar</strong></span><span style=""font-weight: 400;"">, ante tales injusticias del sistema nosotros nos paramos del lado del trabajador a defender sus derechos.</span></p>
							<p><strong>Le recordamos que </strong><span style=""text-decoration: underline;""><strong>el reclamo se realiza directamente a la ART. Su empleador no tiene relaci&oacute;n alguna con el reclamo</strong></span><span style=""font-weight: 400;""> y la indemnizaci&oacute;n que reciba usted proviene &uacute;nicamente de la ART. Al realizar el reclamo usted no perjudica de ningun modo a su patron ni pone en riesgo su trabajo.</span></p>
							<p><span style=""font-weight: 400;"">Es fundamental resaltar este punto ya que </span><strong>mucha gente cree que al hacer un reclamo por accidente laboral perjudica a su empleador y por tener una idea equivocada elige resignar sus derechos.</strong></p>
							<p><strong><strong>Cons&uacute;ltenos</strong><span style=""font-weight: 400;""> y le explicaremos de qu&eacute; forma cobrar lo que responde sin arriesgar su empleo.</span></strong></p>";
					break;


				case "enfermedadesProfesionales":
					longDesc = @"<p><span style=""font-weight: 400;"">Las </span><strong>enfermedades</strong><span style=""font-weight: 400;""> profesionales son aquellas </span><strong>producidas por causa del trabajo</strong><span style=""font-weight: 400;"">, a aquellos trabajadores que prestan tareas expuestos a factores de riesgo, como ser: movimientos forzosos y repetitivos, ruidos en el ambiente de trabajo, manipulaci&oacute;n de sustancias qu&iacute;micas e inhalaci&oacute;n de gases, entre otros.</span></p>
							<p><span style=""font-weight: 400;"">La Ley de Riesgos del Trabajo (Ley 24.557) las define en su art&iacute;culo sexto como &ldquo;aquellas que se encuentran incluidas en el listado que elaborar&aacute; y revisar&aacute; el Poder Ejecutivo, conforme al procedimiento del art&iacute;culo 40 apartado 3 de esta ley. El listado identificar&aacute; agente de riesgo, cuadros cl&iacute;nicos, exposici&oacute;n y actividades en capacidad de determinar la enfermedad profesional.&rdquo;</span></p>
							<p><span style=""text-decoration: underline;""><strong>Ejemplo 1</strong></span><strong>:</strong><span style=""font-weight: 400;""> El trabajador, mec&aacute;nico industrial, </span><strong>expuesto a altos niveles sonoros</strong><span style=""font-weight: 400;""> en el puesto de trabajo, padece hipoacusia bilateral.</span></p>
							<p><span style=""text-decoration: underline;""><strong>Ejemplo 2</strong></span><strong>:</strong><span style=""font-weight: 400;""> El trabajador, operario de m&aacute;quina, expuesto a </span><strong>movimientos repetitivos del hombro derecho</strong><span style=""font-weight: 400;"">, padece tendinitis del hombro.</span></p>
							<p><span style=""text-decoration: underline;""><strong>Ejemplo 3</strong></span><strong>:</strong><span style=""font-weight: 400;""> El trabajador, docente de escuela, expuesto a la </span><strong>sobrecarga del uso de la voz</strong><span style=""font-weight: 400;"">, padece disfon&iacute;a persistente</span></p>
							<p><span style=""font-weight: 400;"">En estos casos, la ART deber&aacute; brindar las prestaciones m&eacute;dicas y dinerarias hasta el alta m&eacute;dica o plazo legal, y si de la enfermedad profesional, han quedado secuelas tanto ps&iacute;quicas como f&iacute;sicas en la salud del trabajador, &eacute;ste tiene el derecho a ser indemnizado conforme la normativa vigente.</span></p>
							<p><strong>Tenga presente que, asi como en el caso de los seguros automotores, el negocio de las ARTs es pagarle a usted lo menos posible. En gran parte de los casos, pese a existir accidentes grav&iacute;simos y pruebas contundentes de secuelas, las ARTs brindan una atenci&oacute;n m&eacute;dica m&iacute;nima y luego le dan el alta al paciente sin ningun tipo de incapacidad o con un porcentaje muy bajo.</strong></p>
							<p><strong>No se deje enga&ntilde;ar</strong><span style=""font-weight: 400;"">, ante tales injusticias del sistema nosotros nos paramos del lado del trabajador a defender sus derechos.</span></p>
							<p><strong>Le recordamos que el reclamo se realiza directamente a la ART. Su empleador no tiene relaci&oacute;n alguna con el reclamo</strong><span style=""font-weight: 400;""> y la indemnizaci&oacute;n que reciba usted proviene &uacute;nicamente de la ART. Al realizar el reclamo usted no perjudica de ningun modo a su patron ni pone en riesgo su trabajo.</span></p>
							<p><span style=""font-weight: 400;"">Es fundamental resaltar este punto ya que </span><strong>mucha gente cree que al hacer un reclamo por accidente laboral perjudica a su empleador y por tener una idea equivocada elige resignar sus derechos.</strong></p>
							<p><strong><strong>Cons&uacute;ltenos</strong><span style=""font-weight: 400;""> y le explicaremos de qu&eacute; forma cobrar lo que responde sin arriesgar su empleo.</span></strong></p>";
					break;

				case "destruccionTotal":
					longDesc = @"<p><span style=""font-weight: 400;"">Si usted o alg&uacute;n familiar/ amigo ha sido v&iacute;ctima de un accidente en el cual su veh&iacute;culo sufri&oacute; una destrucci&oacute;n total, debe asesorarse con profesionales de su confianza que le brinden el </span><strong>mejor servicio al menor costo</strong><span style=""font-weight: 400;"">. Le garantizamos un tr&aacute;mite r&aacute;pido y la mejor atenci&oacute;n para gestionar su </span><strong>indemnizaci&oacute;n</strong><span style=""font-weight: 400;""> brind&aacute;ndole un seguimiento constante de la evoluci&oacute;n de su caso. </span><span style=""text-decoration: underline;""><strong>Tenga presente que no siempre es necesario ir a juicio para lograr el cobro de lo que le corresponde, es por eso que nuestros servicios se adaptan a las necesidades de nuestros clientes a trav&eacute;s de un contacto permanente. </strong></span></p>
								<p><strong>Las compa&ntilde;&iacute;as de seguros, tienen una doble manera de medir si un veh&iacute;culo se encuentra destruido de forma total o no.</strong></p>
								<h3 style=""font-size: 25px;"" ><span style=""text-decoration: underline;""><strong>Cl&aacute;usula 80%</strong></span></h3>
								<p><span style=""font-weight: 400;"">Quienes tengan contratada una cobertura de destrucci&oacute;n total al 80%, deben saber que se considerar&aacute; al autom&oacute;vil como destruido por completo,</span><strong> si el costo de reparar el da&ntilde;o sufrido es superior al 80% del valor de la suma asegurada</strong><span style=""font-weight: 400;""> (el monto que figura en la p&oacute;liza al momento del accidente).</span></p>
								<h3 style=""font-size: 25px;""><span style=""text-decoration: underline;""><strong>Cl&aacute;usula 20%</strong></span></h3>
								<p><span style=""font-weight: 400;"">Cuando tengamos un autom&oacute;vil asegurado con destrucci&oacute;n total al 20%, debemos saber que, en caso de siniestro, </span><strong>se sumar&aacute; el valor de los restos. Si su valor no supera el 20% de la suma asegurada o de mercado, se considera que existe destrucci&oacute;n total.</strong></p>
								<p><strong><strong>&nbsp;</strong></strong></p>
								<p><span style=""text-decoration: underline;""><strong>Por qu&eacute; es importante saber esto? </strong></span></p>
								<p><strong><strong>&nbsp;</strong></strong></p>
								<p><span style=""font-weight: 400;"">Porque cuando existe destrucci&oacute;n total, en vez de reclamarle al seguro del tercero se reclama al </span><strong>propio seguro</strong><span style=""font-weight: 400;"">, quien </span><strong>deber&aacute; indemnizarlo por el valor total de su veh&iacute;culo.</strong></p>
								<p><span style=""font-weight: 400;"">El </span><strong>problema </strong><span style=""font-weight: 400;"">se presenta cuando </span><strong>usted plantea a su seguro la existencia de destrucci&oacute;n total y el mismo no se quiere hacerse cargo de la indemnizaci&oacute;n</strong><span style=""font-weight: 400;"">.</span> <span style=""font-weight: 400;"">En todos los casos,</span><strong> la controversia gira alrededor de cual es el porcentaje (%) de destrucci&oacute;n que el seguro reconoce. Este siempre ser&aacute; inferior al 80% necesario para que usted cobre en su seguro deslig&aacute;ndose asi del tema y deriv&aacute;ndolo al seguro del tercero.</strong><span style=""font-weight: 400;""> Los casos m&aacute;s graves se presentan cuando usted tuvo la responsabilidad del choque, dado que, de ser asi, el seguro del tercero tampoco cubre los da&ntilde;os sufridos por su veh&iacute;culo.</span></p>
								<p><span style=""font-weight: 400;"">Para definirlo con mayor claridad,</span><strong> aunque usted haya tenido la responsabilidad del choque, si existe destrucci&oacute;n total de su veh&iacute;culo, su seguro debe cubrirle el valor total del coche.</strong></p>
								<p><strong>Cuando usted se asesora con nosotros debe saber que contamos con el conocimiento necesario para que la compa&ntilde;&iacute;a de seguros asuma la responsabilidad y que le pague el m&aacute;ximo obtenible. Nuestro importante caudal de reclamos facilita imponer al seguro condiciones de negociaci&oacute;n m&aacute;s favorables para usted. </strong><span style=""font-weight: 400;"">Tenga presente adem&aacute;s que las compa&ntilde;&iacute;as de seguro pagan por riesgo judicial. Es decir que</span><strong> cuando interviene un abogado, el seguro, ante la posibilidad de afrontar un juicio termina pag&aacute;ndole a usted m&aacute;s para evitar los costos del mismo.</strong></p>
								<p><strong><span style=""font-weight: 400;"">Recuerde que usted cuenta con </span><strong>dos a&ntilde;os para iniciar </strong><span style=""font-weight: 400;"">el </span><strong>reclamo</strong><span style=""font-weight: 400;"">. No deje pasar el tiempo y reciba lo que le corresponde.</span></strong></p>";
					break;





			}

			var model = new ServiceModel
			{
				LongDesc = longDesc,
				ServiceName = GetServiceName(service),
				ContactModel = new ContactModel()
			};
			return View(model);
		}

		private string GetServiceName(string service)
		{
			var ret = "";
			switch (service)
			{
				case "accidentesEnTransportePublico":
					ret = "ACCIDENTES EN TRANSPORTE PUBLICO";
					break;
				case "accidentesEnAuto":
					ret = "ACCIDENTES EN AUTO";
					break;
				case "accidentesEnMoto":
					ret = "ACCIDENTES EN MOTO";
					break;
				case "accidentesEnBicicleta":
					ret = "ACCIDENTES EN BICICLETA";
					break;
				case "accidentesComoAcompanantes":
					ret = "ACCIDENTES COMO ACOMPAÑANTE";
					break;
				case "accidentesComoPeaton":
					ret = "ACCIDENTES COMO PEATON";
					break;
				case "choqueSinSeguro":
					ret = "CHOCÓ Y NO TENÍA PAGO SU SEGURO";
					break;
				case "destruccionTotal":
					ret = "DESTRUCCIÓN TOTAL";
					break;
				case "accidentesDeTrabajo":
					ret = "ACCIDENTES EN OCASIÓN DEL TRABAJO";
					break;
				case "accidentesInItinere":
					ret = "ACCIDENTES IN ITINERE (CAMINO AL TRABAJO, O DE REGRESO A CASA)";
					break;

				case "enfermedadesProfesionales":
					ret = "ENFERMEDADES PROFESIONALES";
					break;
			}
			return ret;
		}
	}
}
